#some tips: http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
site_name: Qi Docs
site_description: Documenation for the Qi service
site_favicon: '/img/qi-docs-favicon.ico'
copyright: Copyright &copy; 2015, OSIsoft, LLC <style type="text/css">.wy-nav-content-wrap{Background:none!important;}</style>
docs_dir: docs
repo_url: https://github.com/osisoft/Qi-Docs
# theme: sphinx_rtd_theme

pages:
- Introduction: 'index.md'
- API reference: #'Qi Service API Reference.md'
  - Overview: 'Overview.md'
  - Video: 'Videos.md'
  - QiTypes: 'QiTypes.md'
  - QiStreams: 'QiStreams.md'
  - QiStreamBehaviors: 'QiStreamBehaviors.md'
  - Writing data: 'Writing data.md'
  - Reading data: 'Reading data.md'
  - Filter expressions: 'Filter Expressions.md'
- Samples:  'samples.md'
- Preview: 'preview.md'
- Support:  'support.md'
